// Code generated by hertz generator.

package product

import (
	"gomall/app/frontend/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	return nil
}


func _deleteproductMw() []app.HandlerFunc {
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Auth(),
		middleware.RBAC(middleware.RoleProductPermissions),
	}
}

func _updateMw() []app.HandlerFunc {
	return nil
}
