// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: verifycode.proto

package server

import (
	"context"

	"easy-chat/apps/verifyCode/rpc/internal/logic"
	"easy-chat/apps/verifyCode/rpc/internal/svc"
	"easy-chat/apps/verifyCode/rpc/verifyCode"
)

type VerifyCodeServer struct {
	svcCtx *svc.ServiceContext
	verifyCode.UnimplementedVerifyCodeServer
}

func NewVerifyCodeServer(svcCtx *svc.ServiceContext) *VerifyCodeServer {
	return &VerifyCodeServer{
		svcCtx: svcCtx,
	}
}

func (s *VerifyCodeServer) GetVerifyCode(ctx context.Context, in *verifyCode.GetVerifyCodeRequest) (*verifyCode.GetVerifyCodeReply, error) {
	l := logic.NewGetVerifyCodeLogic(ctx, s.svcCtx)
	return l.GetVerifyCode(in)
}
