version: '3'

services:
  etcd:
    image: etcd:v3.5.5
    container_name: etcd
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://10.0.0.17:3379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      easy-chat:

  redis:
    image: redis:7.2.5
    ports:
      - 16379:6379
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:
    command: redis-server --requirepass easy-chat --appendonly yes

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: easy-chat
    restart: always
    networks:
      easy-chat:

  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: easy-chat
    ports:
      - 47017:27017
    volumes:
      - ./components/mongo/data:/data/db
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      easy-chat:

  zookeeper:
    image: zookeeper:3.7.1
    ports:
      - 2181:2181
    container_name: zookeeper
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:

  kafka:
    image: kafka:3.6
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ws2ms_chat:8:1,ms2ps_chat:8:1,msg_to_mongo:8:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://10.0.0.17:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    depends_on:
      - zookeeper
    networks:
      easy-chat:

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.0-alpine
    container_name: apisix-dashboard
    restart: always
    depends_on:
      - etcd
    volumes:
      - ./components/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      easy-chat:

  apisix:
    image: apache/apisix:3.9.1-debian
    container_name: apisix
    restart: always
    depends_on:
      - etcd
      - apisix-dashboard
    volumes:
      - ./components/apisix/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./components/apisix/logs:/usr/local/apisix/logs
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9093:9093/tcp"
    networks:
      easy-chat:

  sail:
    image: sail:latest
    container_name: sail
    ports:
      - "8108:8108"
    volumes:
      - "./components/sail/compose-cfg.toml:/app/cfg.toml"
    restart: always
    platform: linux/arm64
    #networks:
    #  easy-chat:

  jaeger:
    image: jaegertracing/all-in-one:1.56.0
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: always
    networks:
      easy-chat:

  elasticsearch:
    image: elasticsearch:7.17.3
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    restart: always
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      easy-chat:

  kibana:
    image: kibana:7.17.3
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    container_name: kibana
    restart: always
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      easy-chat:

  logstash:
    image: logstash:7.17.2
    container_name: logstash
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/logstash/logs:/usr/share/logstash/logs
      - ./components/mysql/data/aee9e8b8a52f-slow.log:/var/logs/mysql-slow.log
      - ./components/apisix/logs:/var/logs/apisix
      - ./components/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - '5044:5044'
      - '50000:50000/tcp'
      - '50000:50000/udp'
      - '9600:9600'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      easy-chat:

  prometheus:
    image: prometheus:v2.34.0
    container_name: prometheus
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./components/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./components/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    user: root
    ports:
      - 9090:9090
    networks:
      easy-chat:

  grafana:
    image: grafana:8.3.3
    container_name: grafana
    volumes:
      - ./components/grafana/config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./components/grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
      - "10007:10007"
    depends_on:
      - prometheus
    privileged: true
    user: root
    networks:
      easy-chat:

networks:
  easy-chat:
    driver: bridge