// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: verifycode.proto

package verifycodeclient

import (
	"context"

	"easy-chat/apps/verifyCode/rpc/verifyCode"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetVerifyCodeReply   = verifyCode.GetVerifyCodeReply
	GetVerifyCodeRequest = verifyCode.GetVerifyCodeRequest

	VerifyCode interface {
		GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeReply, error)
	}

	defaultVerifyCode struct {
		cli zrpc.Client
	}
)

func NewVerifyCode(cli zrpc.Client) VerifyCode {
	return &defaultVerifyCode{
		cli: cli,
	}
}

func (m *defaultVerifyCode) GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeReply, error) {
	client := verifyCode.NewVerifyCodeClient(m.cli.Conn())
	return client.GetVerifyCode(ctx, in, opts...)
}
