// Code generated by Kitex v0.9.1. DO NOT EDIT.

package checkoutservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	checkout "gomall/rpc_gen/kitex_gen/checkout"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Checkout(ctx context.Context, Req *checkout.CheckoutReq, callOptions ...callopt.Option) (r *checkout.CheckoutResp, err error)
	PreCheckout(ctx context.Context, Req *checkout.PreCheckoutReq, callOptions ...callopt.Option) (r *checkout.PreCheckoutResp, err error)
	ContinueCheckout(ctx context.Context, Req *checkout.ContinueCheckoutReq, callOptions ...callopt.Option) (r *checkout.ContinueCheckoutResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCheckoutServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCheckoutServiceClient struct {
	*kClient
}

func (p *kCheckoutServiceClient) Checkout(ctx context.Context, Req *checkout.CheckoutReq, callOptions ...callopt.Option) (r *checkout.CheckoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Checkout(ctx, Req)
}

func (p *kCheckoutServiceClient) PreCheckout(ctx context.Context, Req *checkout.PreCheckoutReq, callOptions ...callopt.Option) (r *checkout.PreCheckoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreCheckout(ctx, Req)
}

func (p *kCheckoutServiceClient) ContinueCheckout(ctx context.Context, Req *checkout.ContinueCheckoutReq, callOptions ...callopt.Option) (r *checkout.ContinueCheckoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ContinueCheckout(ctx, Req)
}
