// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: AIEino.proto

package AIEino

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 处理用户意图的请求消息
type AIWithOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInput string `protobuf:"bytes,1,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"` // 用户输入的文本
	UserId    uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户 ID
}

func (x *AIWithOrdersReq) Reset() {
	*x = AIWithOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AIEino_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIWithOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIWithOrdersReq) ProtoMessage() {}

func (x *AIWithOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_AIEino_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIWithOrdersReq.ProtoReflect.Descriptor instead.
func (*AIWithOrdersReq) Descriptor() ([]byte, []int) {
	return file_AIEino_proto_rawDescGZIP(), []int{0}
}

func (x *AIWithOrdersReq) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *AIWithOrdersReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 处理用户意图的响应消息
type AIWithOrdersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []string `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *AIWithOrdersResp) Reset() {
	*x = AIWithOrdersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AIEino_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIWithOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIWithOrdersResp) ProtoMessage() {}

func (x *AIWithOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_AIEino_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIWithOrdersResp.ProtoReflect.Descriptor instead.
func (*AIWithOrdersResp) Descriptor() ([]byte, []int) {
	return file_AIEino_proto_rawDescGZIP(), []int{1}
}

func (x *AIWithOrdersResp) GetOrders() []string {
	if x != nil {
		return x.Orders
	}
	return nil
}

type AIWithPreCheckoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInput string `protobuf:"bytes,1,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"` // 用户输入的文本
	UserId    uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户 ID
}

func (x *AIWithPreCheckoutReq) Reset() {
	*x = AIWithPreCheckoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AIEino_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIWithPreCheckoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIWithPreCheckoutReq) ProtoMessage() {}

func (x *AIWithPreCheckoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_AIEino_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIWithPreCheckoutReq.ProtoReflect.Descriptor instead.
func (*AIWithPreCheckoutReq) Descriptor() ([]byte, []int) {
	return file_AIEino_proto_rawDescGZIP(), []int{2}
}

func (x *AIWithPreCheckoutReq) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *AIWithPreCheckoutReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AIWithPreCheckoutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreCheckoutRes []string `protobuf:"bytes,1,rep,name=pre_checkout_res,json=preCheckoutRes,proto3" json:"pre_checkout_res,omitempty"`
}

func (x *AIWithPreCheckoutResp) Reset() {
	*x = AIWithPreCheckoutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AIEino_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIWithPreCheckoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIWithPreCheckoutResp) ProtoMessage() {}

func (x *AIWithPreCheckoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_AIEino_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIWithPreCheckoutResp.ProtoReflect.Descriptor instead.
func (*AIWithPreCheckoutResp) Descriptor() ([]byte, []int) {
	return file_AIEino_proto_rawDescGZIP(), []int{3}
}

func (x *AIWithPreCheckoutResp) GetPreCheckoutRes() []string {
	if x != nil {
		return x.PreCheckoutRes
	}
	return nil
}

var File_AIEino_proto protoreflect.FileDescriptor

var file_AIEino_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x41, 0x49, 0x45, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x41, 0x49, 0x45, 0x69, 0x6e, 0x6f, 0x22, 0x49, 0x0a, 0x0f, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x2a, 0x0a, 0x10, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x4e, 0x0a,
	0x14, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x41, 0x0a,
	0x15, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x65, 0x5f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x70, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x32, 0xa4, 0x01, 0x0a, 0x0d, 0x41, 0x49, 0x45, 0x69, 0x6e, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x17, 0x2e, 0x41, 0x49, 0x45, 0x69, 0x6e, 0x6f, 0x2e, 0x41, 0x49, 0x57, 0x69,
	0x74, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x41, 0x49,
	0x45, 0x69, 0x6e, 0x6f, 0x2e, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x50, 0x0a, 0x11, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x50,
	0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x1c, 0x2e, 0x41, 0x49, 0x45,
	0x69, 0x6e, 0x6f, 0x2e, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x41, 0x49, 0x45, 0x69, 0x6e,
	0x6f, 0x2e, 0x41, 0x49, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x6f, 0x6d, 0x61, 0x6c,
	0x6c, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f,
	0x67, 0x65, 0x6e, 0x2f, 0x41, 0x49, 0x45, 0x69, 0x6e, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_AIEino_proto_rawDescOnce sync.Once
	file_AIEino_proto_rawDescData = file_AIEino_proto_rawDesc
)

func file_AIEino_proto_rawDescGZIP() []byte {
	file_AIEino_proto_rawDescOnce.Do(func() {
		file_AIEino_proto_rawDescData = protoimpl.X.CompressGZIP(file_AIEino_proto_rawDescData)
	})
	return file_AIEino_proto_rawDescData
}

var file_AIEino_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_AIEino_proto_goTypes = []interface{}{
	(*AIWithOrdersReq)(nil),       // 0: AIEino.AIWithOrdersReq
	(*AIWithOrdersResp)(nil),      // 1: AIEino.AIWithOrdersResp
	(*AIWithPreCheckoutReq)(nil),  // 2: AIEino.AIWithPreCheckoutReq
	(*AIWithPreCheckoutResp)(nil), // 3: AIEino.AIWithPreCheckoutResp
}
var file_AIEino_proto_depIdxs = []int32{
	0, // 0: AIEino.AIEinoService.AIWithOrders:input_type -> AIEino.AIWithOrdersReq
	2, // 1: AIEino.AIEinoService.AIWithPreCheckout:input_type -> AIEino.AIWithPreCheckoutReq
	1, // 2: AIEino.AIEinoService.AIWithOrders:output_type -> AIEino.AIWithOrdersResp
	3, // 3: AIEino.AIEinoService.AIWithPreCheckout:output_type -> AIEino.AIWithPreCheckoutResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AIEino_proto_init() }
func file_AIEino_proto_init() {
	if File_AIEino_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AIEino_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIWithOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AIEino_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIWithOrdersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AIEino_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIWithPreCheckoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AIEino_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIWithPreCheckoutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AIEino_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AIEino_proto_goTypes,
		DependencyIndexes: file_AIEino_proto_depIdxs,
		MessageInfos:      file_AIEino_proto_msgTypes,
	}.Build()
	File_AIEino_proto = out.File
	file_AIEino_proto_rawDesc = nil
	file_AIEino_proto_goTypes = nil
	file_AIEino_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.1. DO NOT EDIT.

type AIEinoService interface {
	AIWithOrders(ctx context.Context, req *AIWithOrdersReq) (res *AIWithOrdersResp, err error)
	AIWithPreCheckout(ctx context.Context, req *AIWithPreCheckoutReq) (res *AIWithPreCheckoutResp, err error)
}
