// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aieinoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	AIEino "gomall/rpc_gen/kitex_gen/AIEino"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AIWithOrders(ctx context.Context, Req *AIEino.AIWithOrdersReq, callOptions ...callopt.Option) (r *AIEino.AIWithOrdersResp, err error)
	AIWithPreCheckout(ctx context.Context, Req *AIEino.AIWithPreCheckoutReq, callOptions ...callopt.Option) (r *AIEino.AIWithPreCheckoutResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIEinoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIEinoServiceClient struct {
	*kClient
}

func (p *kAIEinoServiceClient) AIWithOrders(ctx context.Context, Req *AIEino.AIWithOrdersReq, callOptions ...callopt.Option) (r *AIEino.AIWithOrdersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AIWithOrders(ctx, Req)
}

func (p *kAIEinoServiceClient) AIWithPreCheckout(ctx context.Context, Req *AIEino.AIWithPreCheckoutReq, callOptions ...callopt.Option) (r *AIEino.AIWithPreCheckoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AIWithPreCheckout(ctx, Req)
}
