// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
	"gomall/app/frontend/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.Auth()}
}

func _orderlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
