// Code generated by hertz generator.

package aieino

import (
	"github.com/cloudwego/hertz/pkg/app"
	"gomall/app/frontend/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.Auth()}
}

func _ailistorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aisetorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aiMw() []app.HandlerFunc {
	// your code...
	return nil
}
