scrape_configs:
  - job_name: user
    metrics_path: /metrics
    static_configs:
      - targets:
          - user-svc:9990

  - job_name: product
    metrics_path: /metrics
    static_configs:
      - targets:
          - product-svc:9991

  - job_name: cart
    metrics_path: /metrics
    static_configs:
      - targets:
          - cart-svc:9992

  - job_name: payment
    metrics_path: /metrics
    static_configs:
      - targets:
          - payment-svc:9993

  - job_name: checkout
    metrics_path: /metrics
    static_configs:
      - targets:
          - checkout-svc:9994

  - job_name: order
    metrics_path: /metrics
    static_configs:
      - targets:
          - order-svc:9995

  - job_name: email
    metrics_path: /metrics
    static_configs:
      - targets:
          - email-svc:9996

  - job_name: aieino
    metrics_path: /metrics
    static_configs:
      - targets:
          - aieino-svc:9997

  - job_name: frontend
    metrics_path: /metrics
    static_configs:
      - targets:
          - frontend-svc:9998


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for HTTP 200 response.
    static_configs:
      - targets:
          - http://192.168.10.16:30080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-svc:9115  # The blackbox exporter's real hostname:port.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-svc:9093
rule_files:
  - "alert_rules.yml"
