scrape_configs:
  - job_name: myapp-test
    metrics_path: /metrics
    static_configs:
      - targets:
          - ['10.0.0.16:1234']

  - job_name: user-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - "10.0.0.16:7888"

  - job_name: user-rpc
    metrics_path: /metrics
    static_configs:
      - targets:
          - "10.0.0.16:10070"

